Dedicated Host Changes - Initial update
terraform-ibm-modules/terraform-ibm-dedicated-host pull request #6
Opened 2024-12-12 03:58 UTC by Louies-Jhony

### Description
Dedicated Host module for deploying VSI's. This is related to the [GIT Issue](https://github.ibm.com/GoldenEye/issues/issues/11513)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

##### Release notes content

No release

### Run the pipeline

NA

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

2024-12-12 17:00 UTC, ocofaigh requested changes
I left an initial round of comments. There are other updates needed in the readme and the tests, but we can iterate on that after these initial comments are addressed.

I also see no differences between the basic and advanced examples? Ideally they should do something different - but the module is so simple, maybe there is no need for an Advanced example at all?

2024-12-12 17:00 UTC, ocofaigh commented on variables.tf
> +  description = "Family defines the purpose of the dedicated host, The dedicated host family can be defined from balanced,compute or memory. Refer [Understanding DH Profile family](https://cloud.ibm.
also that url could probably be shortened to https://cloud.ibm.com/docs/vpc?topic=vpc-dh-profiles&interface=ui

2024-12-12 17:00 UTC, ocofaigh commented on variables.tf
> +  type        = string
suggest to add a default value

2024-12-12 17:00 UTC, ocofaigh commented on variables.tf
>    description = "List of resource tag to associate with the instance."
`resource_tags` is not used anywhere?

2024-12-12 17:00 UTC, ocofaigh commented on variables.tf
> +  description = "Name of the dedicated host and dedicated host group"
I would split this into 2 separate inputs

2024-12-12 17:00 UTC, ocofaigh commented on main.tf
> +  name           = "${var.name}-dhgrp"
as per my other comment, create separate inputs for host group name and host name, and don't add any characters here like you have done (`-dhgrp`). People like to have full control over naming

2024-12-12 17:00 UTC, ocofaigh commented on main.tf
> +  name           = "${var.name}-dh"
as per my other comment, create separate inputs for host group name and host name, and don't add any characters here like you have done (`-dh`). People like to have full control over naming

2024-12-12 17:00 UTC, ocofaigh commented on examples/basic/version.tf
> +      version = ">= 1.65.0, < 2.0.0"
can you lock this into the lowest version that the module supports so we always have a test that tests that version still works

2024-12-12 17:00 UTC, ocofaigh commented on examples/basic/version.tf
> +  required_version = ">= 1.3.0"
>= 1.9.0

2024-12-12 17:00 UTC, ocofaigh commented on examples/basic/variables.tf
> +}
please do not expose profile, class, family or zone in the example. Simply hard code sample values in the main.tf of the example. Its only an example, its not designed to be a flexible solution.

2024-12-12 17:00 UTC, ocofaigh commented on examples/basic/variables.tf
> +variable "name" {
please add back prefix and use for the naming within the example code. We use prefix in the test framework so we can generate and use a unique prefix for every test so names don't clash

2024-12-12 17:00 UTC, ocofaigh commented on examples/advanced/version.tf
> +  required_version = ">= 1.3.0"
>= 1.9.0

2024-12-12 17:00 UTC, ocofaigh commented on examples/advanced/variables.tf
> +}
again, dont expose all these vars

2024-12-12 17:00 UTC, ocofaigh commented on examples/advanced/README.md
> +## Requirements
dont add a Requirements section to an example

2024-12-13 06:52 UTC, Louies-Jhony commented on version.tf
> +  required_version = ">= 1.3.0"
Version has been updated to 1.9.0

2024-12-13 07:04 UTC, Louies-Jhony commented on variables.tf
> +  description = "Family defines the purpose of the dedicated host, The dedicated host family can be defined from balanced,compute or memory. Refer [Understanding DH Profile family](https://cloud.ibm.
- URL for the class has been updated.
- Updated from host to host group.

2024-12-13 07:05 UTC, Louies-Jhony commented on variables.tf
> +  default     = "balanced"
- Added validation for choosing from the provided values from (memory, compute, balanced).

2024-12-13 07:06 UTC, Louies-Jhony commented on variables.tf
> +  type        = string
- Added us-south-1 as the default zone.

2024-12-13 08:13 UTC, Louies-Jhony commented on variables.tf
> +  description = "Profile class of the dedicated host, this has to be defined based on the VSI usage. Refer [Understanding DH Class](https://cloud.ibm.com/docs/vpc?topic=vpc-dh-profiles&interface=ui#:
- Updated for the descirption

2024-12-13 08:16 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +variable "name" {
- Updated name to prefix.

2024-12-13 08:25 UTC, Louies-Jhony commented on variables.tf
> +  description = "Name of the dedicated host and dedicated host group"
- Defined as common

2024-12-13 08:29 UTC, Louies-Jhony commented on main.tf
> +  name           = "${var.name}-dhgrp"
- Kept prefix as name for both dedicated host and dedicated host group

2024-12-13 08:29 UTC, Louies-Jhony commented on main.tf
> +  name           = "${var.name}-dh"
- Kept prefix as name for both dedicated host and dedicated host group

2024-12-13 08:30 UTC, Louies-Jhony commented on examples/basic/version.tf
> +  required_version = ">= 1.3.0"
- Updated to 1.9.0

2024-12-13 08:30 UTC, Louies-Jhony commented on examples/advanced/version.tf
> +  required_version = ">= 1.3.0"
- Updated to 1.9.0 version

2024-12-13 08:58 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +}
- Removed from variables and added to main.tf file.

2024-12-13 09:01 UTC, Louies-Jhony commented on examples/advanced/variables.tf
> +}
- Updated

2024-12-13 09:02 UTC, Louies-Jhony commented on examples/advanced/README.md
> +## Requirements
- Updated as suggested

2024-12-13 11:22 UTC, Louies-Jhony commented on variables.tf
>    description = "List of resource tag to associate with the instance."
- Resource tags are added.

2024-12-13 11:24 UTC, Louies-Jhony commented on examples/basic/version.tf
> +      version = ">= 1.65.0, < 2.0.0"
- Locked to the lowest version.

2024-12-13 11:25 UTC, Louies-Jhony commented on version.tf
> +      version = ">= 1.65.0, < 2.0.0"
- Had a initial fail during the build, re-verified and no issue on the 1.71.2 version. Updated to the same.

2024-12-17 13:11 UTC, ocofaigh requested changes
I left some more comments, however as discussed internally if we want to give consumers full control over naming, I don't think we should implement this way using a prefix input. 
We might look to use a complex input such as [this](https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/1b4e49fd569111ef126bb19a1bbbfd0e41b442c8/variables.tf#L97-L111) (TBC internally)

2024-12-17 13:11 UTC, ocofaigh commented on tests/pr_test.go
> +const resourceGroup = "HPCC"
please change this back

2024-12-17 13:11 UTC, ocofaigh commented on examples/basic/variables.tf
> +}
the variables have not been removed?

2024-12-17 13:11 UTC, ocofaigh commented on examples/basic/variables.tf
> +  description = "The name of the resource group where you want to create the service."
can you add back the default value of `null`? It means if value is null, example will create new resource group

2024-12-17 20:10 UTC, ocofaigh commented
@Louies-Jhony As discussed internally, lets go with the approach of 1 complex object input in the module (maybe call it `dedicated_host`?). The following schema should work:
```
type = list(object({
    dedicated_host_group_name          = string
    resource_group_id                  = string
    existing_dedicated_host_group_name = optional(bool, false)
    class                              = optional(string, "bx2")
    family                             = optional(string, "balanced")
    zone                               = optional(string, "us-south-1")
    dedicated_hosts = list(object({
      name                 = string
      profile              = string
      access_tags          = optional(list, [])
    }))
  }))
```

2024-12-18 13:03 UTC, Louies-Jhony commented on tests/pr_test.go
> +const resourceGroup = "HPCC"
Updated

2024-12-18 13:04 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +  description = "The name of the resource group where you want to create the service."
Updated

2024-12-18 13:06 UTC, Louies-Jhony commented on examples/advanced/README.md
> +# Basic example
Updated

2024-12-18 13:07 UTC, Louies-Jhony commented on examples/advanced/README.md
> +- A new dedicated host group will be created, each dedicated host will be added to the dedicated host group.
Updated

2024-12-18 13:58 UTC, Louies-Jhony commented on README.md
Updated

2024-12-18 14:00 UTC, Louies-Jhony commented
@ocofaigh @toddgiguere 

- Changes are updated, kindly review and let me know any changes required.
- Need update on Advanced example and help on Access policies.

2024-12-18 17:09 UTC, toddgiguere requested changes

2024-12-18 17:09 UTC, toddgiguere commented on main.tf
> +  }
See comment above, and in variables comment, using a boolean to determine existing or not might be easier than relying on name being not null.

2024-12-18 17:09 UTC, toddgiguere commented on main.tf
> +  name           = each.value.host_group_name != null ? each.value.host_group_name : "${var.prefix}"
Also just realized "var.prefix" is not going to work here, since the input is a list of many groups + hosts, you will need more than one group name.

2024-12-18 17:09 UTC, toddgiguere commented on variables.tf
> +    host_group_name   = optional(string, null)
Agree with this statement, and about the prefix, also commented in main.tf that prefix is not going to work for new group names, since technically this is a list of objects, meaning a consumer could use this module to create MANY groups, not just one. That means each new host group needs a unique name, so having one prefix will not work.

Switching to having host_group_name always required, along with the existing boolean, will make this work if consumer wants to set up multiple groups in this input.

2024-12-18 17:09 UTC, toddgiguere commented on version.tf
>    required_version = ">= 1.9.0"
Is v1.9.0 required for this module? or can we allow >=1.3.0 if we are not using 1.9 features?

2024-12-18 17:13 UTC, ocofaigh commented on version.tf
>    required_version = ">= 1.9.0"
@toddgiguere All new modules should be >= 1.9 (we update module template). We are going to bump all our modules to this

2024-12-19 04:40 UTC, Louies-Jhony commented on examples/advanced/variables.tf
> +}
- Its been updated already, kindly refer the latest commit.

2024-12-19 04:42 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +  description = "The name of the resource group where you want to create the service."
Its been updated already, kindly refer the latest commit.

2024-12-19 04:47 UTC, Louies-Jhony commented on variables.tf
> +    host_group_name   = optional(string, null)
- The changes been reverted now with a boolean value.

2024-12-19 05:01 UTC, Louies-Jhony commented on variables.tf
> +variable "dedicated_hosts_group" {
- The values are associated with the group, there is a separate list object for dedicated host inside the variable.

2024-12-19 05:04 UTC, Louies-Jhony commented on variables.tf
> +variable "prefix" {
- Removed.

2024-12-19 05:05 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +  type        = string
- Its been updated already, kindly refer the latest commit.

2024-12-19 05:06 UTC, Louies-Jhony commented on examples/basic/variables.tf
> +  default = ["env:test"]
- Yes renamed to access tags, terraform has no support for resource tags on dedicated host.

2024-12-19 05:06 UTC, Louies-Jhony commented on examples/basic/main.tf
> +          access_tags = ["env:test"]
- Updated

2024-12-19 05:07 UTC, Louies-Jhony commented on main.tf
> +  name           = each.value.host_group_name != null ? each.value.host_group_name : "${var.prefix}"
- Updated

2024-12-19 05:07 UTC, Louies-Jhony commented on main.tf
> +  }
Updated

2024-12-19 14:19 UTC, toddgiguere requested changes

2024-12-19 14:19 UTC, toddgiguere commented on examples/basic/main.tf
> +      host_group_name     = "basic-dhgroup"
This is the spot where you want to use prefix, to make sure there is a unique name for the resource. "${var.prefix}-dhgroup" for example.

Then in your unit test, you would provide a prefix like "basic", our testwrapper will assign a random string to that, and the result would be something like "basic-awgyu-dhgroup". This will avoid name clashes in the account when tests are running in parallel, or if a previous failed test had failed to fully destroy.

Also use same prefix for the name of the host below.

2024-12-19 14:19 UTC, toddgiguere commented on examples/basic/main.tf
> +      resource_group_id   = "0808a9d6f8874342b7c4c07ad1666dc2"
This should not be hard-coded, this is the output of the resource_group module above.

2024-12-19 15:18 UTC, toddgiguere commented on main.tf
> +        key               = "${group_obj}-${host_obj}"
Consider changing key so that instead of index you are using more stable value, such as concatenation of names (group+host)

2024-12-19 15:24 UTC, toddgiguere commented on examples/basic/main.tf
> +  resource_group_name          = var.resource_group == null ? "dhbasic-resource-group" : null
change back to "${var.prefix}-resource-group"

2024-12-19 15:25 UTC, toddgiguere commented on examples/basic/main.tf
> +      resource_group_id   = "0808a9d6f8874342b7c4c07ad1666dc2"
will be module.resource_group.resource_group_id

2024-12-19 15:26 UTC, toddgiguere commented on examples/basic/variables.tf
> -variable "resource_group" {
Need to add back in var.resource_group (for unit tests)

2024-12-19 15:30 UTC, toddgiguere commented on examples/basic/main.tf
> +      zone                = "us-south-1"
Since region is input, can make this "${var.region}-1" to keep example flexible.

2024-12-20 08:40 UTC, Louies-Jhony commented on examples/basic/main.tf
> +      host_group_name     = "basic-dhgroup"
Updated

2024-12-20 08:41 UTC, Louies-Jhony commented on examples/basic/main.tf
> +      resource_group_id   = "0808a9d6f8874342b7c4c07ad1666dc2"
Updated

2024-12-20 08:42 UTC, Louies-Jhony commented on main.tf
> +        key               = "${group_obj}-${host_obj}"
Updated

2024-12-20 08:42 UTC, Louies-Jhony commented on examples/basic/main.tf
> +  resource_group_name          = var.resource_group == null ? "dhbasic-resource-group" : null
Updated

2024-12-20 08:43 UTC, Louies-Jhony commented on examples/basic/variables.tf
> -variable "resource_group" {
Updated

2024-12-20 08:44 UTC, Louies-Jhony commented on examples/basic/main.tf
> +      zone                = "us-south-1"
Updated

2024-12-20 16:40 UTC, Louies-Jhony commented
/run pipeline

2024-12-20 17:58 UTC, toddgiguere requested changes

2024-12-20 17:58 UTC, toddgiguere commented on examples/advanced/main.tf
> +      host_group_name     = "${var.prefix}-dhgroup"
I think this example is not a proper example of how a consumer would add two hosts to the same group. In this module, you wouldn't have two items in the array for the same host_group_name, with one of them being existing true. Instead what it should be is one top level host_group_name, with two hosts in the `dedicated_host` array.

2024-12-20 17:58 UTC, toddgiguere commented on examples/upgrade/variables.tf
> +    ca-tor   = "r038-7b030074-925d-43cf-aecd-6ef97883787e"
I'm not sure if this mapping should go as a default in an input variable. What you could do instead is have this mapping in a locals in the main.tf, and an input of just plain "string" for an image_id, and if that variable is null you could then look one up in your locals map by region.

2024-12-20 17:58 UTC, toddgiguere commented on main.tf
> +  }
I think you only need the data block if the existing flag is true, and not for all new groups as well. You are already taking care of "new or existing" properly down in the host block with a conditional.

This means you should have an if condition on the for_each to only do this data block if existing is true, and you can get rid of the depends_on.

Also I think you mentioned that host groups names must be unique in an account? If that is the case you don't need to use the index of the array as part of the key, just use the host_group_name as the key. Using index is risky as well if the end-user changes the order of the input array.

2024-12-20 19:04 UTC, toddgiguere commented on examples/advanced/main.tf
> +      host_group_name     = "${var.prefix}-dhgroup"
A more advanced example for me would be the following scenario:

Lets say I need hosts in two zones. In each zone I need two hosts, one of which is for VSI that have smaller requirement (cpu, memory, iops), and another host that has a different profile, perhaps huge memory. Let's call these two types "small" and "large".

That would result in the following dedicated_hosts input (note I'm not including all params, just an example):
```hcl
dedicated_hosts = [
{
  host_group_name = "prefix-zone-1"
  zone = "us-south-1"
  dedicated_host = [
    {
      name = "prefix-z1-myhost-small"
      profile = "small"
    },
    {
      name = "prefix-z1-myhost-big"
      profile = "large"
    }
  ]
},
{
  host_group_name = "prefix-zone-2"
  zone = "us-south-2"
  dedicated_host = [
    {
      name = "prefix-z2-myhost-small"
      profile = "small"
    },
    {
      name = "prefix-z2-myhost-big"
      profile = "large"
    }
  ]
}
]
```

2024-12-20 21:59 UTC, Louies-Jhony commented
/run pipeline

2024-12-20 22:05 UTC, Louies-Jhony commented
/run pipeline

2024-12-20 23:04 UTC, Louies-Jhony commented on main.tf
> +  }
- Addressed.

2024-12-20 23:18 UTC, Louies-Jhony commented on examples/upgrade/variables.tf
> +    ca-tor   = "r038-7b030074-925d-43cf-aecd-6ef97883787e"
Updated

2024-12-20 23:42 UTC, Louies-Jhony commented on examples/advanced/main.tf
> +      host_group_name     = "${var.prefix}-dhgroup"
- Updated to the available profiles for different zone.

2024-12-21 01:51 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 05:55 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 08:12 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 08:54 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 09:34 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 20:34 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 20:54 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 21:19 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 22:43 UTC, Louies-Jhony commented
/run pipeline

2024-12-22 23:05 UTC, Louies-Jhony commented
1. All checks are passed and changes are comleted as requested.
2. @imprateeksh  @Aashiq-J Kindly review and merge the changes.

FYI - @ocofaigh @toddgiguere

2024-12-24 05:05 UTC, Aashiq-J commented on tests/pr_test.go
> +// func TestRunAdvancedExample(t *testing.T) {
you will need to add test for all the example if possible, also run an upgrade test on the advanced example.

2024-12-24 05:33 UTC, Louies-Jhony commented on README.md
>  [![latest release](https://img.shields.io/github/v/release/terraform-ibm-modules/terraform-ibm-module-template?logo=GitHub&sort=semver)](https://github.com/terraform-ibm-modules/terraform-ibm-module-
Updated

2024-12-24 05:33 UTC, Louies-Jhony commented on examples/upgrade/main.tf
> +  #  dedicated_host_id          = module.dedicated_host.dedicated_host_group_ids
- As discussed changes has to be updated on VSI module.

2024-12-24 05:34 UTC, Louies-Jhony commented on README.md
>  module "module_template" {
Updated

2024-12-24 05:34 UTC, Louies-Jhony commented on tests/pr_test.go
> +// func TestRunAdvancedExample(t *testing.T) {
- For now Basic test enabled.
- On increasing Quota the advanced test will be enabled.

2024-12-24 05:57 UTC, Aashiq-J commented
/run pipeline

2024-12-24 06:24 UTC, Aashiq-J commented
/run pipeline

2024-12-24 06:26 UTC, Aashiq-J approved these changes
LGTM

2024-12-24 06:33 UTC, merged

2024-12-24 06:34 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-dedicated-host/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: